// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List  = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");

function answer(q, a) {
  return /* record */[
          /* q */q,
          /* a */a
        ];
}

function ask(q) {
  return (function (param) {
      return /* record */[
              /* q */q,
              /* a */param
            ];
    });
}

function quiz3(q1, q2, q3) {
  return /* tuple */[
          (function (param) {
              return /* record */[
                      /* q */q1,
                      /* a */param
                    ];
            }),
          (function (param) {
              return /* record */[
                      /* q */q2,
                      /* a */param
                    ];
            }),
          (function (param) {
              return /* record */[
                      /* q */q3,
                      /* a */param
                    ];
            })
        ];
}

function answer3(a1, a2, a3, q) {
  return /* :: */[
          Curry._1(q[0], a1),
          /* :: */[
            Curry._1(q[1], a2),
            /* :: */[
              Curry._1(q[2], a3),
              /* [] */0
            ]
          ]
        ];
}

var bridgeKeepersQuiz = answer3("Blake", "To learn ReasonML", "Blue", quiz3("What is your name?", "What is your quest?", "What is your favorite color?"));

List.iter((function (prim) {
        console.log(prim);
        return /* () */0;
      }), bridgeKeepersQuiz);

exports.answer            = answer;
exports.ask               = ask;
exports.quiz3             = quiz3;
exports.answer3           = answer3;
exports.bridgeKeepersQuiz = bridgeKeepersQuiz;
/* bridgeKeepersQuiz Not a pure module */
