// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List       = require("bs-platform/lib/js/list.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function average(l) {
  return Caml_int32.div(List.fold_left((function (a, b) {
                    return a + b | 0;
                  }), 0, l), List.length(l));
}

var foo = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* :: */[
        4,
        /* :: */[
          5,
          /* [] */0
        ]
      ]
    ]
  ]
];

console.log(average(foo));

exports.average = average;
exports.foo     = foo;
/*  Not a pure module */
