// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function run1to100(runner) {
  for(var x = 1; x <= 100; ++x){
    Curry._1(runner, x);
  }
  return /* () */0;
}

function isFizz(x) {
  return +(x % 3 === 0);
}

function isBuzz(x) {
  return +(x % 5 === 0);
}

function fizzBuzz(x) {
  var remainder_000 = isFizz(x);
  var remainder_001 = isBuzz(x);
  if (remainder_000 !== 0) {
    if (remainder_001 !== 0) {
      console.log("FizzBuzz");
      return /* () */0;
    } else {
      console.log("Fizz");
      return /* () */0;
    }
  } else if (remainder_001 !== 0) {
    console.log("Buzz");
    return /* () */0;
  } else {
    console.log(x);
    return /* () */0;
  }
}

run1to100(fizzBuzz);

exports.run1to100 = run1to100;
exports.isFizz    = isFizz;
exports.isBuzz    = isBuzz;
exports.fizzBuzz  = fizzBuzz;
/*  Not a pure module */
