// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

var $percent = Caml_int32.mod_;

console.log(2);

console.log(2);

function $pipe$unknown(a, b) {
  if (a) {
    return a;
  } else {
    return b;
  }
}

var someHello = $pipe$unknown($pipe$unknown(/* None */0, /* None */0), /* Some */["Hello"]);

console.log(someHello);

var fiveModThee = 2;

var otherFiveModThree = 2;

exports.$percent          = $percent;
exports.fiveModThee       = fiveModThee;
exports.otherFiveModThree = otherFiveModThree;
exports.$pipe$unknown     = $pipe$unknown;
exports.someHello         = someHello;
/*  Not a pure module */
