// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function compare(c, a, b) {
  if (c !== 0) {
    var match = +(a <= b);
    if (match !== 0) {
      return a;
    } else {
      return b;
    }
  } else {
    var match$1 = +(a >= b);
    if (match$1 !== 0) {
      return a;
    } else {
      return b;
    }
  }
}

function compareList(c, l) {
  return List.fold_left((function (param, param$1) {
                return compare(c, param, param$1);
              }), 0, l);
}

var foo = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* :: */[
        4,
        /* :: */[
          5,
          /* [] */0
        ]
      ]
    ]
  ]
];

console.log(compareList(/* Largest */0, foo));

console.log(compareList(/* Smallest */1, foo));

exports.compare     = compare;
exports.compareList = compareList;
exports.foo         = foo;
/*  Not a pure module */
