// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                      = require("@glennsl/bs-jest/src/jest.js");
var Caml_builtin_exceptions   = require("bs-platform/lib/js/caml_builtin_exceptions.js");
var LinkedList$DataStructures = require("../src/LinkedList.bs.js");

function unwrap(x) {
  if (x) {
    return x[0];
  } else {
    throw [
          Caml_builtin_exceptions.match_failure,
          [
            "/Users/blaketarter/Sites/reasonml-examples/data-structures/__tests__/LinkedList_test.re",
            5,
            32
          ]
        ];
  }
}

describe("LinkedList", (function () {
        Jest.test("Infix Makes Lists", (function () {
                return Jest.ExpectJs[/* toBeDefined */25](Jest.ExpectJs[/* expect */0](LinkedList$DataStructures.Infix[/* @: */0](0, /* Empty */0)));
              }));
        return Jest.test("Head gets first item in LinkedList", (function () {
                      return Jest.Expect[/* toBe */2]("foo", Jest.Expect[/* expect */0](unwrap(LinkedList$DataStructures.head(LinkedList$DataStructures.Infix[/* @: */0]("foo", /* Empty */0)))));
                    }));
      }));

exports.unwrap = unwrap;
/*  Not a pure module */
