// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function sum(l) {
  return List.fold_left((function (a, b) {
                return a + b | 0;
              }), 0, l);
}

var foo = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* :: */[
        4,
        /* :: */[
          5,
          /* [] */0
        ]
      ]
    ]
  ]
];

console.log(sum(foo));

exports.sum = sum;
exports.foo = foo;
/*  Not a pure module */
