// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function get(url) {
  return fetch(url).then((function (prim) {
                  return prim.json();
                })).then((function (prim) {
                return Promise.resolve(prim);
              }));
}

exports.get = get;
/* No side effect */
