// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Json_decode   = require("bs-json/src/Json_decode.js");
var Api$FetchJson = require("./Api.bs.js");

function decodeFilm(json) {
  return /* record */[
          /* title */Json_decode.field("title", Json_decode.string, json),
          /* url */Json_decode.field("url", Json_decode.string, json)
        ];
}

function decodeFilms(json) {
  return Json_decode.field("results", (function (param) {
                return Json_decode.array(decodeFilm, param);
              }), json);
}

function get() {
  return Api$FetchJson.get("https://swapi.co/api/films");
}

exports.decodeFilm  = decodeFilm;
exports.decodeFilms = decodeFilms;
exports.get         = get;
/* No side effect */
