// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Json_decode   = require("bs-json/src/Json_decode.js");
var Api$FetchJson = require("./Api.bs.js");

function decodePerson(json) {
  return /* record */[
          /* name */Json_decode.field("name", Json_decode.string, json),
          /* url */Json_decode.field("url", Json_decode.string, json)
        ];
}

function decodePeople(json) {
  return Json_decode.field("results", (function (param) {
                return Json_decode.array(decodePerson, param);
              }), json);
}

function get() {
  return Api$FetchJson.get("https://swapi.co/api/people");
}

exports.decodePerson = decodePerson;
exports.decodePeople = decodePeople;
exports.get          = get;
/* No side effect */
