// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function make(x) {
  return /* Node */[
          /* [] */0,
          x,
          /* [] */0
        ];
}

function prepend(x, y) {
  var c = y[2];
  var b = y[1];
  var a = y[0];
  if (a) {
    return /* Node */[
            /* :: */[
              x,
              a
            ],
            b,
            c
          ];
  } else {
    return /* Node */[
            /* :: */[
              x,
              /* [] */0
            ],
            b,
            c
          ];
  }
}

function append(x, y) {
  var c = x[2];
  var b = x[1];
  var a = x[0];
  if (c) {
    return /* Node */[
            a,
            b,
            List.rev_append(c, /* :: */[
                  y,
                  /* [] */0
                ])
          ];
  } else {
    return /* Node */[
            a,
            b,
            /* :: */[
              y,
              /* [] */0
            ]
          ];
  }
}

function prev(x) {
  var aRev = List.rev(x[0]);
  if (aRev) {
    return /* Some */[/* Node */[
              aRev[1],
              aRev[0],
              /* :: */[
                x[1],
                x[2]
              ]
            ]];
  } else {
    return /* None */0;
  }
}

function next(x) {
  var c = x[2];
  if (c) {
    return /* Some */[/* Node */[
              List.rev_append(x[0], /* :: */[
                    x[1],
                    /* [] */0
                  ]),
              c[0],
              c[1]
            ]];
  } else {
    return /* None */0;
  }
}

function curr(x) {
  return x[1];
}

function curr$1(x) {
  if (x) {
    return /* Some */[curr(x[0])];
  } else {
    return /* None */0;
  }
}

var Maybe = /* module */[/* curr */curr$1];

var bar = /* Node */[
  /* [] */0,
  "bar",
  /* [] */0
];

var fooBar = prepend("foo", bar);

var fooBarBaz = append(fooBar, "baz");

console.log(fooBarBaz);

console.log(curr(fooBarBaz));

console.log(curr$1(prev(fooBarBaz)));

console.log(curr$1(next(fooBarBaz)));

exports.make      = make;
exports.prepend   = prepend;
exports.append    = append;
exports.prev      = prev;
exports.next      = next;
exports.curr      = curr;
exports.Maybe     = Maybe;
exports.bar       = bar;
exports.fooBar    = fooBar;
exports.fooBarBaz = fooBarBaz;
/* fooBar Not a pure module */
