// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function make(x) {
  return /* Stack */[
          x,
          /* Empty */0
        ];
}

function push(x, y) {
  if (x) {
    return /* Stack */[
            y,
            x
          ];
  } else {
    return /* Stack */[
            y,
            /* Empty */0
          ];
  }
}

function pop(x) {
  if (x) {
    var b = x[1];
    var a = x[0];
    if (b) {
      return /* tuple */[
              /* Some */[a],
              b
            ];
    } else {
      return /* tuple */[
              /* Some */[a],
              /* Empty */0
            ];
    }
  } else {
    return /* tuple */[
            /* None */0,
            /* Empty */0
          ];
  }
}

function peek(x) {
  if (x) {
    return /* Some */[x[0]];
  } else {
    return /* None */0;
  }
}

function length(x) {
  var _x = x;
  var _y = 0;
  while(true) {
    var y = _y;
    var x$1 = _x;
    if (x$1) {
      _y = y + 1 | 0;
      _x = x$1[1];
      continue ;
      
    } else {
      return y;
    }
  };
}

exports.make   = make;
exports.push   = push;
exports.pop    = pop;
exports.peek   = peek;
exports.length = length;
/* No side effect */
