// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function make(x) {
  return /* Tree */[
          x,
          /* Empty */0,
          /* Empty */0
        ];
}

function peek(x) {
  if (x) {
    return /* Some */[x[0]];
  } else {
    return /* None */0;
  }
}

function getLeft(x) {
  if (x) {
    return peek(x[1]);
  } else {
    return /* None */0;
  }
}

function getRight(x) {
  if (x) {
    return peek(x[2]);
  } else {
    return /* None */0;
  }
}

function setLeft(x, y) {
  if (x) {
    return /* Tree */[
            x[0],
            /* Tree */[
              y,
              /* Empty */0,
              /* Empty */0
            ],
            x[2]
          ];
  } else {
    return /* Tree */[
            y,
            /* Empty */0,
            /* Empty */0
          ];
  }
}

function setRight(x, y) {
  if (x) {
    return /* Tree */[
            x[0],
            x[1],
            /* Tree */[
              y,
              /* Empty */0,
              /* Empty */0
            ]
          ];
  } else {
    return /* Tree */[
            y,
            /* Empty */0,
            /* Empty */0
          ];
  }
}

var tree = /* Tree */[
  "root",
  /* Empty */0,
  /* Empty */0
];

var tree$1 = setLeft(tree, "left");

var tree$2 = setRight(tree$1, "right");

console.log(tree$2);

exports.make     = make;
exports.peek     = peek;
exports.getLeft  = getLeft;
exports.getRight = getRight;
exports.setLeft  = setLeft;
exports.setRight = setRight;
exports.tree     = tree$2;
/* tree Not a pure module */
